{
 "title": "Kubernetes Pods",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"^$namespace$\"}, pod)"
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, pod_ip)"
   },
   {
    "name": "phase",
    "label": "Phase",
    "query": "query_result(kube_pod_status_phase{namespace=~\"^$namespace$\", pod=~\"^$pod$\"} == 1)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "content": "<h1><center>$phase</center></h1>"
  },
  {
   "title": "IP",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "content": "<h1><center>$pod_ip</center></h1>"
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Avg CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\"$pod\",job!=\"kubernetes-apiservers\"}[2m]))"
    }
   ]
  },
  {
   "title": "Current Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\",job!=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Avg Network",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[2m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$pod\"}[2m]))"
    }
   ]
  },
  {
   "title": "Avg Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",container_name!=\"POD\",job!=\"kubernetes-apiservers\",pod_name=~\"^$pod$\"}[2m])) + sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",container_name!=\"POD\",job!=\"kubernetes-apiservers\",pod_name=~\"^$pod$\"}[2m]))"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pod NW Transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"^$pod$\",job!=\"kubernetes-nodes\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod NW Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\"^$pod$\",job!=\"kubernetes-nodes\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Container Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "container",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"^$namespace$\",pod_name=~\"^$pod$\",container_name!=\"POD\",job!=\"kubernetes-apiservers\"}) by (container_name)",
     "legendFormat": "Actual: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"^$pod$\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"^$pod$\"}",
     "legendFormat": "Limits: {{ container }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Container CPU Usage Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container_name!=\"POD\",job!=\"kubernetes-apiservers\",pod_name=~\"^$pod$\"}[2m])) by (container_name) ",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Container Disk Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",container_name!=\"POD\",job!=\"kubernetes-apiservers\",pod_name=~\"^$pod$\"}[2m])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Container Disk Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",container_name!=\"POD\",job!=\"kubernetes-apiservers\",pod_name=~\"^$pod$\"}[2m])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  }
 ]
}